package com.muwp.sharding.jdbc.core.impl;

import org.springframework.jdbc.core.PreparedStatementCreator;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * 返回主键的PreparedStatementCreator
 *
 * @author mwup
 * @version 1.0
 * @created 2019/02/15 13:51
 **/
public class ReturnIdPreparedStatementCreator implements PreparedStatementCreator {

    private String sql;

    private Object[] params;

    private String autoGeneratedColumnName;

    public ReturnIdPreparedStatementCreator(String sql, Object[] params, String autoGeneratedColumnName) {
        this.sql = sql;
        this.params = params;
        this.autoGeneratedColumnName = autoGeneratedColumnName;
    }

    @Override
    public PreparedStatement createPreparedStatement(Connection connection) throws SQLException {
        final PreparedStatement ps = connection.prepareStatement(sql, new String[]{autoGeneratedColumnName});
        for (int i = 0; i < params.length; i++) {
            Object value = params[i];
            ps.setObject((i + 1), value);
        }
        return ps;
    }

}
